Update Spanish strings
coderGtm/yantra-app-launcher pull request #150
Opened 2024-06-21 01:51 UTC by jfacdev

Update Spanish strings with updated strings file.

2024-06-21 13:31 UTC, coderGtm approved these changes

2024-06-21 13:35 UTC, coderGtm requested changes
You'd need to update the repo as there are conflicts.

2024-06-21 14:21 UTC, jfacdev commented
Ok, how can I do it?

2024-06-22 16:28 UTC, jfacdev commented
I think it's done now!

2024-06-24 14:16 UTC, closed without merging